// Single source of truth for the About gallery teaser and the deep About page.
// NOTE: items tagged with [ brackets ] are placeholders - replace with your
// real organization / work experience details.

export const aboutIntro =
  "A Software Engineering student who combines technical rigor with human-centered design. Beyond code, I lead teams, shape culture, and turn ideas into systems that matter across web, AI, and robotics.";

// Left page of the "open book" About spread - the personal narrative.
export const aboutStory = {
  paragraphs: [
    "My path into technology began with a simple question: how do the things we use every day actually work? That curiosity grew into a love for building, shaping blank files into systems people can feel, use, and trust.",
    "Today I move between the web, AI, and robotics, not to collect tools, but to understand how an idea becomes something real. And I care just as much about the people behind the product: leading teams, shaping culture, and making the work mean something.",
  ],
};

// Education + Work + Organization. `tag` drives the About "Field Notes"
// filter (Education | Work | Organization) and the deep About page.
const ICON_EDU = 'M12 14l9-5-9-5-9 5 9 5z M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z';
const ICON_WORK = 'M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z';
const ICON_ORG = 'M17 20h5v-2a4 4 0 00-3-3.87M9 20H4v-2a4 4 0 013-3.87m6-1.13a4 4 0 10-4-4 4 4 0 004 4zM7 10a4 4 0 108 0 4 4 0 00-8 0z';
const ICON_BOT = 'M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 7h10v10H7V7z';

export const experiences = [
  // ---------------------------- Education ----------------------------
  {
    tag: 'Education',
    org: 'UPN Veteran Jawa Timur',
    role: 'S1 Informatika, Faculty of Computer Science',
    period: '2024 - Present',
    summary: 'Studying software engineering, AI, and robotics.',
    description: "Currently pursuing a Bachelor's degree in Informatics at the Faculty of Computer Science, focusing on software engineering, intelligent systems, and robotics with real-world applications.",
    gradient: 'from-blue-600 to-indigo-500',
    icon: ICON_EDU,
  },
  {
    tag: 'Education',
    org: 'Pijar Foundation',
    role: 'Future Skills, Business Economics & Algorithm Literacy',
    period: '2025',
    summary: 'Score 3.80 in economics and algorithm literacy.',
    description: "Completed the Future Skills program with a final score of 3.80, covering Business Economics and Algorithm Literacy, blending economic reasoning with analytical and data-driven decision making.",
    gradient: 'from-blue-500 to-cyan-400',
    icon: ICON_EDU,
  },
  {
    tag: 'Education',
    org: 'SMA Negeri 1 Tarik',
    role: 'Science (K13 Curriculum)',
    period: 'Graduated',
    summary: 'Graduated with honors, score 94.26 out of 100.',
    description: "Graduated with high honors scoring 94.26 out of 100 under the Science K13 Curriculum, building a strong foundation in mathematics and natural sciences for advanced studies.",
    gradient: 'from-indigo-500 to-purple-500',
    icon: ICON_EDU,
  },

  // ------------------------------ Work -------------------------------
  {
    tag: 'Work',
    org: 'Affection Organizer',
    role: 'Crew And IT Analyst',
    period: '',
    photos: ['/assets/affection-1.jpg', '/assets/affection-2.jpg'],
    summary: 'IT systems, digital security & external communications.',
    description: "• Designed and managed internal IT systems supporting organizational operations, including participant data structures, access control, and integration between cloud-based and on-premises divisions.\n• Developed and implemented ethically-grounded digital security policies: data encryption, risk management, and privacy protocols to maintain information integrity and trust.\n• Managed external communications with clients, partners, and the public through proposals, activity reports, and representative materials reflecting professionalism and institutional values.\n• Coordinated synchronization between technical and communications teams, keeping documentation, publications, and operational workflows consistent, responsive, and compliant with institutional standards.",
    gradient: 'from-fuchsia-600 to-pink-500',
    icon: ICON_WORK,
  },
  {
    tag: 'Work',
    org: 'PPMB UPN Veteran Jawa Timur',
    role: 'Public Relations',
    period: '',
    photos: ['/assets/humas-upn-1.jpeg', '/assets/humas-upn-2.jpg'],
    summary: 'Admissions communication strategy & PR.',
    description: "• Designed and managed institutional communication strategies for New Student Admissions, including publication materials, social media management, and information coordination between units.\n• Developed official narratives and public responses reflecting institutional values, answering prospective students and parents professionally, accurately, and representatively.\n• Coordinated with technical and academic teams to synchronize information across the registration system, selection schedule, and public communication channels.\n• Managed external channels with school partners, media, and the community through official letters, activity proposals, and publication reports.\n• Built a documentation system for accountability and reporting.",
    gradient: 'from-blue-600 to-indigo-500',
    icon: ICON_WORK,
  },
  {
    tag: 'Work',
    org: 'TikTok SNL & Tokopedia',
    role: 'Marketing & Talent',
    period: '',
    photos: ['/assets/marketing-1.jpg', '/assets/marketing-2.jpg'],
    summary: 'Digital marketing, content & talent direction.',
    description: "• Designed and executed digital marketing strategies for plain and custom-design apparel, covering market segmentation, visual positioning, and narrative appeal on the TikTok platform.\n• Managed direct-sales campaigns and promotional content: script writing, talent direction, and real-time audience interaction flows to lift conversion and engagement.\n• Coordinated with design and production teams to keep product identity, promotional materials, and market expectations consistent across Tokopedia and TikTok Shop channels.",
    gradient: 'from-rose-500 to-orange-400',
    icon: ICON_WORK,
  },
  {
    tag: 'Work',
    org: 'Ciputra Surabaya & GADAS',
    role: 'Programmer & Game Designer',
    period: '',
    photos: ['/assets/ggj-1.jpg', '/assets/ggj-2.jpg'],
    summary: 'Game programming & scalable system design.',
    description: "• Designed a social-interaction and educational game system using a modular approach and logic validation, enabling feature expansion such as leaderboards, reward systems, and dynamic event triggers.\n• Developed a structured, scalable code architecture covering input systems, collision detection, scoring logic, and visual integration via sprite animation and UI layers.\n• Implemented mechanics blending casual and competitive elements (inspired by models like Garena Bubble Boba): daily challenges, skin unlocks, and in-game currency.\n• Debugged and optimized cross-device performance with bottleneck analysis and root-cause diagnostics for stability and responsiveness.",
    gradient: 'from-indigo-600 to-purple-600',
    icon: ICON_WORK,
  },
  {
    tag: 'Work',
    org: 'ELVANOR, UPA UPNVJT',
    role: 'Business Analyst & UI/UX Designer',
    period: '',
    photos: ['/assets/elvanor-2.jpg', '/assets/formal-blue.jpg'],
    summary: 'Business analysis & UI/UX for a product platform.',
    description: "• Led the design of a business system based on natural-ingredient research, with a standardized, tested product formulation ready for institutional and commercial-scale development.\n• Built the internal organizational structure, established cross-functional workflows (production, branding, distribution, finance), and set up quality-control and periodic performance-evaluation mechanisms.\n• Designed a product-positioning strategy uniting sustainability, local identity, and market competitiveness through brand narrative, packaging design, and digital distribution channels.\n• Managed institutional communications with external partners, campus units, and user communities through proposals, performance reports, and impact-driven advocacy campaigns.\n• Developed a showcase-ready reporting system combining production data, market analysis, and impact visualization as an internal evaluation tool and institutional representation for competitions, publications, and expansion.",
    gradient: 'from-purple-600 to-fuchsia-500',
    icon: ICON_WORK,
  },

  // -------------------------- Organization ---------------------------
  {
    tag: 'Organization',
    org: 'Duta SMA Negeri 1 Tarik',
    role: 'Chairman of School Ambassadors, Sidoarjo',
    period: '',
    photos: ['/assets/duta-smanstar-1.jpg'],
    summary: 'Led the school ambassador program.',
    description: "• Led the transformation of the School Ambassador program from a representative symbol into a strategic platform for student diplomacy, values advocacy, and strengthening the institution's image.\n• Designed a cadre-development system grounded in communication competency, public ethics, and collective leadership.\n• Initiated external partnerships with educational institutions and local communities to widen the reach of the school's representation.",
    gradient: 'from-amber-500 to-orange-500',
    icon: ICON_ORG,
  },
  {
    tag: 'Organization',
    org: 'OSIS SMA Negeri 1 Tarik (SECKID 9)',
    role: 'Member, Sidoarjo, Indonesia',
    period: '',
    photos: ['/assets/osis-1.jpeg'],
    summary: 'OSIS documentation & internal communication.',
    description: "• Managed the organization's digital documentation system including meeting minutes, policy archives, and cross-sector accountability reports.\n• Developed an internal OSIS communication protocol to ensure narrative consistency and efficient coordination between divisions.\n• Acted as liaison between the OSIS structure and school management in the student-policy formulation process.\n• Drove a work-program evaluation system based on social-impact indicators and student participation.",
    gradient: 'from-cyan-600 to-blue-500',
    icon: ICON_ORG,
  },
  {
    tag: 'Organization',
    org: 'IKATANDANS Sidoarjo',
    role: 'Public Relations Department, Sidoarjo',
    period: '',
    photos: ['/assets/ikatandans-1.jpg', '/assets/ikatandans-2.jpg'],
    summary: 'PR & anti-narcotics advocacy campaigns.',
    description: "• Led the strategic re-branding of IKATANDANS' public image as a credible, youth-led force in anti-narcotics advocacy across Sidoarjo.\n• Designed and implemented an integrated communication campaign targeting schools, communities, and local governments to raise drug-prevention awareness.\n• Developed an internal communication protocol for narrative consistency and operational clarity across departments.\n• Produced exhibition-ready documentation and visual assets for advocacy, reporting, and external representation.\n• Led diplomacy and media-relations efforts to position IKATANDANS as a credible, collaborative student organization.",
    gradient: 'from-rose-500 to-pink-500',
    icon: ICON_ORG,
  },
  {
    tag: 'Organization',
    org: 'Robotika UPN Veteran Jawa Timur',
    role: 'Wheeled KRSBI Programmer, "Nakula"',
    period: '',
    photos: ['/assets/robotic-1.jpg', '/assets/robotic-2.jpg'],
    summary: 'Wheeled soccer-robot control programmer.',
    description: "• Designed and implemented a wheeled soccer-robot control system based on navigation, decision-making, and inter-unit communication algorithms.\n• Developed a modular software architecture supporting integration of sensors, actuators, and real-time game strategies.\n• Collaborated across divisions (mechanical, electronics, strategy) to align the physical design with system logic.\n• Optimized robot performance through debugging, simulation, and field testing in preparation for the national Indonesian Robot Contest (KRSBI).",
    gradient: 'from-emerald-600 to-teal-500',
    icon: ICON_BOT,
  },
  {
    tag: 'Organization',
    org: 'ARMADIRO 1.0',
    role: 'System Architect, Surabaya',
    period: '',
    photos: ['/assets/armadiro-1.jpg', '/assets/armadiro-2.jpg'],
    summary: 'Autonomous sorting robotic-arm architect.',
    description: "• Designed the ARMADIRO 1.0 system architecture: an autonomous robotic arm for sorting items by visual classification, weight, and dimensions.\n• Built a sensor data-processing pipeline (camera, distance, weight) integrated with a decision-tree classification algorithm and rule-based logic.\n• Developed a high-precision motor-control system for dynamic picking and moving, with low error tolerance and fast response time.\n• Implemented a modular ROS (Robot Operating System) framework for functional expansion and interoperability between subsystems.\n• Ran multi-scale simulations and trials measuring sorting accuracy, cycle-time efficiency, and robustness under intensive operation.",
    gradient: 'from-teal-600 to-cyan-500',
    icon: ICON_BOT,
  },
  {
    tag: 'Organization',
    org: 'GenBI UPNVJT & Jatim',
    role: 'Member, New Generation of Indonesia',
    period: '',
    photos: ['/assets/genbi.jpg', '/assets/genbi-2.jpg'],
    summary: 'Bank Indonesia financial & social literacy.',
    description: "• Took part in financial- and social-literacy activities initiated by Bank Indonesia at campus and East Java regional levels.\n• Supported internal and external events including technical coordination, publications, and activity documentation.\n• Built communication, teamwork, and leadership skills through active involvement in student programs and social activities.",
    gradient: 'from-amber-500 to-yellow-400',
    icon: ICON_ORG,
  },
];

export const education = [
  {
    period: '2024 - Present',
    school: 'UPN Veteran Jawa Timur',
    detail: 'Informatics student, Faculty of Computer Science, Informatics study program.',
  },
  {
    period: '2025',
    school: 'Pijar Foundation',
    detail: 'Score 3.80, Business Economics & Corporate Algorithm Literacy.',
  },
  {
    period: 'Graduated',
    school: 'SMA Negeri 1 Tarik',
    detail: 'Score 94.26 / 100.00, Science (K13 Curriculum).',
  },
];

export const skillCategories = [
  { title: 'Languages', skills: ['JavaScript', 'TypeScript', 'Python', 'C++', 'Java'] },
  { title: 'Frameworks', skills: ['Vue.js', 'React.js', 'Next.js', 'Node.js', 'Express.js'] },
  { title: 'Tools / DevOps', skills: ['Git & GitHub', 'Docker', 'Google Cloud', 'Figma'] },
  { title: 'Soft Skills', skills: ['Leadership', 'Problem Solving', 'Team Management', 'Critical Thinking'] },
];

// ===================== Skills & Expertise =====================
// Proficiency bars grouped by domain. `level` is a 0–100 percentage.
// Used by SkillsSection.vue (the animated bar overview on the home page).
export const expertiseAreas = [
  {
    title: 'Software Development',
    accent: 'from-violet-500 to-purple-500',
    icon: 'M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4',
    skills: [
      { name: 'Web Development (Vue / React / Next.js)', level: 90 },
      { name: 'Backend & APIs (Node.js / Express)', level: 85 },
      { name: 'JavaScript / TypeScript', level: 90 },
      { name: 'Databases & Cloud', level: 75 },
    ],
  },
  {
    title: 'UI/UX Design',
    accent: 'from-fuchsia-500 to-pink-500',
    icon: 'M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z',
    skills: [
      { name: 'Figma & Prototyping', level: 88 },
      { name: 'Design Systems', level: 85 },
      { name: 'Responsive / Interaction Design', level: 90 },
      { name: 'User Research', level: 75 },
    ],
  },
  {
    title: 'AI & Data',
    accent: 'from-cyan-500 to-blue-500',
    icon: 'M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 7h10v10H7V7z',
    skills: [
      { name: 'Python', level: 85 },
      { name: 'Algorithms & Problem Solving', level: 85 },
      { name: 'Data Analysis', level: 80 },
      { name: 'Machine Learning', level: 75 },
    ],
  },
  {
    title: 'Leadership & Strategy',
    accent: 'from-emerald-500 to-teal-500',
    icon: 'M17 20h5v-2a4 4 0 00-3-3.87M9 20H4v-2a4 4 0 013-3.87m6-1.13a4 4 0 10-4-4 4 4 0 004 4zM7 10a4 4 0 108 0 4 4 0 00-8 0z',
    skills: [
      { name: 'Team Leadership', level: 90 },
      { name: 'Project Management', level: 85 },
      { name: 'Business Analysis', level: 85 },
      { name: 'Critical Thinking', level: 90 },
    ],
  },
];

// ===================== Gallery / Documentation =====================
// Shown inside the "Read the full story" book. Drop real photos into
// /public/assets and add { src, caption } entries. `placeholder: true`
// renders an empty "add documentation" tile.
export const galleryItems = [
  { src: '/assets/genbi.jpg', caption: 'GenBI Community', tall: true },
  { src: '/assets/formal-blue.jpg', caption: 'Professional Portrait' },
  { src: '/assets/profile.jpg', caption: 'On Campus', tall: true },
  { placeholder: true, caption: 'Add documentation' },
  { placeholder: true, caption: 'Add documentation' },
  { placeholder: true, caption: 'Add documentation' },
  { placeholder: true, caption: 'Add documentation' },
  { placeholder: true, caption: 'Add documentation' },
];

// ================= Certifications & Championships ==================
// Seeded from your existing programs/events - verify and edit freely.
// Add an `image` (e.g. '/assets/your-cert.jpg') to attach documentation.
export const achievements = [
  {
    type: 'Scholarship',
    title: 'GenBI Scholarship',
    issuer: 'Bank Indonesia',
    year: '2025',
    description: 'Awardee of the Bank Indonesia scholarship and a member of the GenBI community, contributing to social and educational initiatives.',
    accent: 'from-amber-500 to-orange-500',
    image: '/assets/genbi.jpg',
  },
  {
    type: 'Certification',
    title: 'HR Management & Organizational Development',
    issuer: 'People, Culture & Leadership',
    year: '2024',
    description: 'Certified in human resource management and organizational development, covering team leadership, change management, and building a high-performing culture.',
    accent: 'from-fuchsia-500 to-purple-500',
    image: '/assets/formal-blue.jpg',
  },
  {
    type: 'Program',
    title: 'Future Skills Group',
    issuer: 'Pijar Foundation',
    year: '2025',
    description: 'Selected for an intensive cohort blending business economics with algorithmic literacy and data-driven decision making.',
    accent: 'from-blue-500 to-cyan-500',
    image: '/assets/profile.jpg',
  },
  {
    type: 'Championship',
    title: 'PMW 2025',
    issuer: 'Program Mahasiswa Wirausaha',
    year: '2025',
    description: 'Recognized in the student entrepreneurship program for ELVANOR, a standardized natural-ingredient product platform.',
    accent: 'from-rose-500 to-orange-500',
    image: null,
  },
  {
    type: 'Championship',
    title: 'Global Game Jam 2024',
    issuer: 'BubbleGum',
    year: '2024',
    description: 'Built BubbleGum, an interactive social educational game, during the worldwide Global Game Jam.',
    accent: 'from-indigo-500 to-purple-500',
    image: null,
  },

  // ---- Courses, bootcamps, webinars & training ----
  {
    type: 'Certification',
    title: 'Prompt Engineering for Software Developers',
    issuer: 'Dicoding',
    year: '2025',
    description: 'Course on prompt engineering techniques to boost software development workflows with generative AI.',
    accent: 'from-violet-500 to-purple-500',
    file: '/assets/certs/prompt-engineering.pdf',
  },
  {
    type: 'Certification',
    title: 'Belajar Dasar AI',
    issuer: 'Dicoding',
    year: '2025',
    description: 'Foundational course covering core concepts of artificial intelligence and its applications.',
    accent: 'from-blue-500 to-cyan-500',
    file: '/assets/certs/dasar-ai.pdf',
  },
  {
    type: 'Certification',
    title: 'Belajar Dasar SQL',
    issuer: 'Dicoding',
    year: '2025',
    description: 'Fundamentals of SQL, covering querying, filtering, and managing relational databases.',
    accent: 'from-emerald-500 to-teal-500',
    file: '/assets/certs/dasar-sql.pdf',
  },
  {
    type: 'Certification',
    title: 'Belajar Data Science',
    issuer: 'Dicoding',
    year: '2025',
    description: 'Introduction to the data science workflow, covering data wrangling, analysis, and insight generation.',
    accent: 'from-cyan-500 to-blue-500',
    file: '/assets/certs/data-science.pdf',
  },
  {
    type: 'Certification',
    title: 'Memulai Pemrograman dengan Python',
    issuer: 'Dicoding',
    year: '2025',
    description: 'Getting started with programming using Python, covering syntax, logic, and problem solving.',
    accent: 'from-amber-500 to-yellow-500',
    file: '/assets/certs/python.pdf',
  },
  {
    type: 'Certification',
    title: 'Belajar Dasar Google Cloud',
    issuer: 'Dicoding',
    year: '2025',
    description: 'Foundational concepts of cloud computing and core Google Cloud services.',
    accent: 'from-sky-500 to-indigo-500',
    file: '/assets/certs/google-cloud.pdf',
  },
  {
    type: 'Certification',
    title: 'Introduction to Financial Literacy',
    issuer: 'Dicoding',
    year: '2025',
    description: 'Essentials of personal financial literacy, covering budgeting, saving, and financial decision making.',
    accent: 'from-green-500 to-emerald-500',
    file: '/assets/certs/financial-literacy.pdf',
  },
  {
    type: 'Certification',
    title: 'Dasar Penggunaan Generative AI',
    issuer: 'Codepolitan, Ruang AI',
    year: '2025',
    description: 'Fundamentals of using generative AI tools effectively in real-world tasks.',
    accent: 'from-fuchsia-500 to-pink-500',
    file: '/assets/certs/generative-ai.pdf',
  },
  {
    type: 'Program',
    title: 'Microsoft ElevAIte Y26',
    issuer: 'Microsoft',
    year: '2026',
    description: 'Selected participant in Microsoft ElevAIte Y26, an AI-focused capacity-building program.',
    accent: 'from-blue-500 to-indigo-500',
    file: '/assets/certs/elevaite-y26.pdf',
  },
  {
    type: 'Program',
    title: 'Webinar ElevAIte Y26',
    issuer: 'Microsoft',
    year: '2026',
    description: 'Attended the Microsoft ElevAIte Y26 webinar on AI skills and industry applications.',
    accent: 'from-indigo-500 to-blue-500',
    file: '/assets/certs/elevaite-webinar.pdf',
  },
  {
    type: 'Program',
    title: 'GARUDA Program',
    issuer: 'Microsoft',
    year: '2025',
    description: 'Participant in the Microsoft GARUDA program advancing digital and AI talent in Indonesia.',
    accent: 'from-cyan-500 to-sky-500',
    image: '/assets/certs/microsoft-garuda.jpg',
    file: '/assets/certs/microsoft-garuda.jpg',
  },
  {
    type: 'Program',
    title: 'Bootcamp Certificate',
    issuer: 'Bootcamp Program',
    year: '2025',
    description: 'Completion of an intensive bootcamp program covering applied technical skills.',
    accent: 'from-purple-500 to-fuchsia-500',
    image: '/assets/certs/bootcamp.png',
    file: '/assets/certs/bootcamp.png',
  },
  {
    type: 'Certification',
    title: 'Softskills & Greenskills Training',
    issuer: 'Training Completion',
    year: '2025',
    description: 'Certified training in soft skills and green skills for the modern workplace.',
    accent: 'from-green-500 to-lime-500',
    file: '/assets/certs/softskills-greenskills.pdf',
  },
  {
    type: 'Certification',
    title: 'Bahasa Inggris dalam Bekerja',
    issuer: 'Training Completion',
    year: '2025',
    description: 'Completion certificate for professional English in the workplace.',
    accent: 'from-rose-500 to-pink-500',
    file: '/assets/certs/english-at-work.pdf',
  },
  {
    type: 'Certification',
    title: 'Graphic Design',
    issuer: 'Training Completion',
    year: '2025',
    description: 'Completion certificate covering graphic design fundamentals and tooling.',
    accent: 'from-pink-500 to-rose-500',
    file: '/assets/certs/graphic-design.pdf',
  },
  {
    type: 'Certification',
    title: 'Microsoft Excel',
    issuer: 'Training Completion',
    year: '2025',
    description: 'Completion certificate for Microsoft Excel, covering formulas, data handling, and analysis.',
    accent: 'from-emerald-500 to-green-500',
    file: '/assets/certs/microsoft-excel.pdf',
  },
  {
    type: 'Program',
    title: 'DevFest Cloud Surabaya',
    issuer: 'Google Developer Groups',
    year: '2025',
    description: 'Participant at DevFest Cloud Surabaya, a community tech conference on cloud and development.',
    accent: 'from-sky-500 to-blue-500',
    image: '/assets/certs/devfest-cloud.jpg',
    file: '/assets/certs/devfest-cloud.jpg',
  },
  {
    type: 'Program',
    title: 'InfraDigital',
    issuer: 'InfraDigital',
    year: '2025',
    description: 'Participation in an InfraDigital program/event focused on digital infrastructure.',
    accent: 'from-indigo-500 to-violet-500',
    image: '/assets/certs/infradigital.jpg',
    file: '/assets/certs/infradigital.jpg',
  },
  {
    type: 'Program',
    title: 'Digistar',
    issuer: 'Telkom Indonesia',
    year: '2025',
    description: 'Selected participant in the Digistar talent-development program.',
    accent: 'from-red-500 to-rose-500',
    file: '/assets/certs/digistar.pdf',
  },
  {
    type: 'Program',
    title: 'Exploration Program',
    issuer: 'Exploration',
    year: '2025',
    description: 'Completion of an exploration program building applied and exploratory skills.',
    accent: 'from-teal-500 to-cyan-500',
    file: '/assets/certs/exploration.pdf',
  },
  {
    type: 'Program',
    title: 'Rakashena',
    issuer: 'Rakashena',
    year: '2025',
    description: 'Participation certificate for the Rakashena program.',
    accent: 'from-amber-500 to-orange-500',
    file: '/assets/certs/rakashena.pdf',
  },
  {
    type: 'Program',
    title: 'Sekolah Pasar Modal, IDX',
    issuer: 'Indonesia Stock Exchange (IDX)',
    year: '2025',
    description: 'Completed capital-market training (Sekolah Pasar Modal) by the Indonesia Stock Exchange.',
    accent: 'from-green-500 to-teal-500',
    file: '/assets/certs/idx-pasar-modal.pdf',
  },
  {
    type: 'Certification',
    title: 'Webinar: IT AI Automation',
    issuer: 'Webinar Certificate',
    year: '2025',
    description: 'Attended a webinar on IT and AI automation and its industry applications.',
    accent: 'from-violet-500 to-indigo-500',
    file: '/assets/certs/webinar-ai-automation.pdf',
  },
  {
    type: 'Certification',
    title: 'Webinar: Persiapan Karir',
    issuer: 'Learnhub',
    year: '2025',
    description: 'Career-preparation webinar in collaboration with Learnhub.',
    accent: 'from-blue-500 to-purple-500',
    file: '/assets/certs/webinar-karir-learnhub.pdf',
  },
  {
    type: 'Certification',
    title: 'Webinar X Danacita',
    issuer: 'Danacita',
    year: '2025',
    description: 'Participation certificate for a webinar held in collaboration with Danacita.',
    accent: 'from-cyan-500 to-teal-500',
    file: '/assets/certs/webinar-danacita.pdf',
  },
  {
    type: 'Program',
    title: 'Paper, Santika',
    issuer: 'Academic Submission',
    year: '2025',
    description: 'Authored paper submission associated with the Santika program/event.',
    accent: 'from-fuchsia-500 to-purple-500',
    file: '/assets/certs/paper-santika.pdf',
  },
  {
    type: 'Certification',
    title: 'Certificate of Participation',
    issuer: 'General',
    year: '2025',
    description: 'General certificate of participation and completion.',
    accent: 'from-slate-400 to-slate-500',
    file: '/assets/certs/certificate-general.pdf',
  },
];
